### ISSUE TITLE
PRECOMPILED VERSION

### ISSUE THREAD

**Issue by SirNapkin1334** [MarcuzD/DiscordCTR#1]
Can someone PLEASE send me a precompiled version? I spent 15 minutes getting all the dependancies, and some of then just didn't work, and I troubleshooted, and I just can't compile it. Can someone please give me a precompiled version?

**Comment by 110Percent** [comment]
You can find the precompiled versions in the out/ folder.

**Comment by SirNapkin1334** [comment]
Dammit.
