### ISSUE TITLE
Instant disconnect, requested gateway no longer supported, discord API issue?

### ISSUE THREAD

**Issue by shanzenos** [MarcuzD/DiscordCTR#3]
Getting the following error once it starts a connection: 

WS handler data: op=8, datalen=0x3D (61)
WS close status=4012
Reason: Requested gateway version is no longer supported or invalid
Disconnecting

I'm assuming it's an issue with discord's API changing again?

**Comment by MarcuzD** [comment]
sorry, the public version is no longer maintained
